# Generated by Django 3.2.3 on 2023-07-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriteslist',
            name='unique_user_recipe',
        ),
        migrations.RemoveField(
            model_name='favoriteslist',
            name='recipe',
        ),
        migrations.AddField(
            model_name='favoriteslist',
            name='recipe',
            field=models.ManyToManyField(related_name='favoriteslist', to='recipe.Recipe', verbose_name='Рецепт в избранном'),
        ),
    ]
