# Generated by Django 3.2.3 on 2023-08-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20230804_1755'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='recipe_subscription_unique_relationships',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='recipe_subscription_unique_relationships'),
        ),
    ]
