# Generated by Django 3.2.3 on 2023-08-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20230804_1757'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='recipe_subscription_unique_relationships',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='to_user',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_subscribe'),
        ),
    ]
