# Generated by Django 3.2.3 on 2023-08-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='is_subscribed',
        ),
    ]
